# Netlify Configuration for Green Givers Nursery
# Domain: greengiversnursery.in

[build]
  # Build command for React app
  command = "npm run build"
  # Directory to publish
  publish = "build"
  # Environment file for build
  environment = { NODE_ENV = "production" }

[build.environment]
  REACT_APP_API_URL = "https://api.greengiversnursery.in"
  REACT_APP_DOMAIN = "https://greengiversnursery.in"
  REACT_APP_NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https: blob:; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.greengiversnursery.in"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# API proxy (if backend is on subdomain)
[[redirects]]
  from = "/api/*"
  to = "https://api.greengiversnursery.in/api/:splat"
  status = 200
  force = true
